// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function IMAPConnect(arg1:Record<string, any>):Promise<boolean>;

export function IMAPDisconnect():Promise<boolean>;

export function IMAPPing():Promise<boolean>;

export function IMAPSearch(arg1:string):Promise<Array<Record<string, any>>>;

export function SaveFile(arg1:string,arg2:Array<number>):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;
