// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IMAPConnect(arg1) {
  return window['go']['main']['App']['IMAPConnect'](arg1);
}

export function IMAPDisconnect() {
  return window['go']['main']['App']['IMAPDisconnect']();
}

export function IMAPPing() {
  return window['go']['main']['App']['IMAPPing']();
}

export function IMAPSearch(arg1) {
  return window['go']['main']['App']['IMAPSearch'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}
